# @Author: Guan Gui <guiguan>
# @Date:   2016-06-02T14:58:00+10:00
# @Email:  root@guiguan.net
# @Last modified by:   guiguan
# @Last modified time: 2018-01-24T11:53:25+11:00

extends: airbnb
env:
  browser: false
  node: true
  es6: true
rules:
  no-continue: 0
  no-labels: 0
  arrow-body-style: 0
  key-spacing: 0
  object-property-newline: 0
  no-cond-assign: [error, except-parens]
  no-nested-ternary: 0
  no-shadow: 0
  eqeqeq: 0
  array-callback-return: 0
  no-param-reassign: 0
  space-before-function-paren: 0
  global-require: 0
  consistent-return: 0
  quote-props: 0
  linebreak-style: 0
  no-underscore-dangle: 0
  prefer-const: [error, {ignoreReadBeforeAssign: true}]
  max-len: 0
  prefer-template: 0
  object-curly-spacing: 0
  comma-dangle: [error, never]
  indent: 0
  no-console: 0
  no-alert: 0
  no-multiple-empty-lines: [2, {max: 3}]
  func-names: 0
  new-cap: [2, {capIsNew: false}]
  import/default: 0
  import/no-duplicates: 0
  import/named: 0
  import/namespace: 0
  import/no-named-as-default: 2
  # this requires eslint-import-resolver-node@0.3.0 to be installed in order for import/resolver settings to work
  import/no-unresolved: [2, {ignore: ["^[~]", "^[#]"]}]
  import/prefer-default-export: 0
  import/no-extraneous-dependencies: 0
  import/extensions: 0
  no-unused-vars: [error, {argsIgnorePattern: ^_}]
  no-restricted-syntax: 0
  no-unused-expressions: 0
  newline-per-chained-call: 0
  no-undef: 0
  class-methods-use-this: 0
  no-multi-str: 0
  no-useless-escape: 0
  no-use-before-define: [error, {functions: false, classes: true}]
  no-mixed-operators: 0
  no-return-assign: [error, except-parens]
  no-prototype-builtins: 0
plugins: [import]
settings:
  import/resolver:
    node:
      moduleDirectory:
        - node_modules
        - src
