# @Author: Guan Gui <guiguan>
# @Date:   2018-01-24T14:35:24+11:00
# @Email:  root@guiguan.net
# @Last modified by:   guiguan
# @Last modified time: 2018-01-25T17:19:53+11:00
#
# dbKoda - a modern, open source code editor, for MongoDB.
# Copyright (C) 2017-2018 Southbank Software
#
# This file is part of dbKoda.
#
# dbKoda is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# dbKoda is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with dbKoda.  If not, see <http://www.gnu.org/licenses/>.

os: linux
dist: trusty
sudo: required
language: node_js
# Node version specified in .nvmrc
node_js: null
jdk: openjdk8

git:
  depth: 3
  submodules: false

before_install:
  - git submodule update --init --recursive --recommend-shallow --remote

install:
  - node -v
  - java -version
  - python --version

script:
  - set -e


deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: cloud-build
  skip_cleanup: true
  local_dir: dbkoda/dist/s3
  region: ap-southeast-2

notifications:
  slack:
    rooms:
      - secure: yveGJdFyDmZ8CnKfr7sATKola4X57GtLTUYlRp8uvxj/ljavwVlR+fczNRJjoAaRdcoYm5GGomKvnJTPJeKAmI62Xjqih0bdxX31WyExjvTuQ6pwzkAVwheV79+kkj49LvPeqLRa0WrKm69orVPlDkpXVi0pdHTXMFj5TbCfMcCzyUKZr53+gqcLl5YKoydOehIK1lL+hW7DB+MSoGY7ayjYsD6Oy+2oOffSYB+b+UtsX2y4ZncjK5vFkNQmSODcaHbneryjR5g9b9joo1KFDbbchy1zXbJDFqWUzbi/t2s9+KypZX48CKolsyd0s6L6ayUZpE/eKdIMkntEpg6Ie48VimPmHjmlvg/z0K+8Bql/7sD/JyADjswZE/KnzyDIO0GvxUmCS99rj71cRCClQv/dO1K7vcHXFebYJ15jFchH3rkEo0NXY5fxY50CkBDELpCopl+oF852pIkWeKG3jUNKp3saBBOYP9q+21+fAtBMykUdQTiRjFWo2xQLbJN8tUdsBfQPZPajD1ywJVlpmR/e1jH107ak1iP4D1GOEqp1f4nGgpqm5SCb77QSMSzhTQRj6gGoGfi0dhwnkCsPLVSUadgPTN36pVrEEDtaVTf1YXtZ3iXGRdgjT3h/RiF8fJemk/VWdprFbJHk+474Z6mJDC6IMkjciNFlyF8YnQY=
    template:
      - 'Linux cloud build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) by %{author} %{result} in %{duration}: %{message}'
  email: false
